[package]
name = "hello_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.5.0"
bevy = {version = "0.18.0"}

[features]
debug = ["bevy/dynamic_linking", "bevy/debug", "bevy/dev"]

[profile.release]
opt-level = "z"  # Optimize for size
lto = true
codegen-units = 1
